// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAmwgr_5C9mig-74JC7Yfi4hzrthgJqW0',
    appId: '1:458475264666:web:7f606fe6e38a0ea4fa5d23',
    messagingSenderId: '458475264666',
    projectId: 'ecoflow-fc41c',
    authDomain: 'ecoflow-fc41c.firebaseapp.com',
    storageBucket: 'ecoflow-fc41c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3nLIS3eSNzKETP-qequS61D3h3x68ld0',
    appId: '1:458475264666:android:c45ac7e1a3a15c1ffa5d23',
    messagingSenderId: '458475264666',
    projectId: 'ecoflow-fc41c',
    storageBucket: 'ecoflow-fc41c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRW27al2LZ6_iGVe1sqX0EMMuHqfa0Uos',
    appId: '1:458475264666:ios:f8628d9c63b2ae9ffa5d23',
    messagingSenderId: '458475264666',
    projectId: 'ecoflow-fc41c',
    storageBucket: 'ecoflow-fc41c.firebasestorage.app',
    iosBundleId: 'com.example.ecoflowapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRW27al2LZ6_iGVe1sqX0EMMuHqfa0Uos',
    appId: '1:458475264666:ios:f8628d9c63b2ae9ffa5d23',
    messagingSenderId: '458475264666',
    projectId: 'ecoflow-fc41c',
    storageBucket: 'ecoflow-fc41c.firebasestorage.app',
    iosBundleId: 'com.example.ecoflowapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAmwgr_5C9mig-74JC7Yfi4hzrthgJqW0',
    appId: '1:458475264666:web:edda6ad3175d6021fa5d23',
    messagingSenderId: '458475264666',
    projectId: 'ecoflow-fc41c',
    authDomain: 'ecoflow-fc41c.firebaseapp.com',
    storageBucket: 'ecoflow-fc41c.firebasestorage.app',
  );
}
